bölge=input("plaka gir")
if bölge=="37": print("kastamonu")
elif bölge=="34": print("istambul")
elif bölge=="57": print("sinop")
elif bölge=="55": print("samsun")
elif bölge=="31": print("hatay")
elif bölge=="45": print("manisa")
elif bölge=="32": print("1sparta")
elif bölge=="60": print("tokat")
elif bölge=="79": print("kilis")
elif bölge=="80": print("osmaniye")
